### ISSUE TITLE
May I ask if this is the source code of the paper? It seems that the code does not implement Verifiable Witness Encryption Based on Threshold Signatures.

### ISSUE THREAD

**Issue by gaobirou** [alfonzii/dlc-fast-prototyping#1]

**Comment by alfonzii** [comment]
Hi @gaobirou, thanks for your input.

You are right, it does not implement VWEBoTS yet. It's work in progress, I have it as my thesis. I'll be however uploading further updates here in meantime.

**Comment by gaobirou** [comment]
> Hi @gaobirou, thanks for your input.
> 
> You are right, it does not implement VWEBoTS yet. It's work in progress, I have it as my thesis. I'll be however uploading further updates here in meantime.

Thank you for your reply!
